# Selected variables for pulling data based on requirements for Figure 3
selected_vars:
    - TRANSPARENCY_REPORT_FKEY       # Unique identifier for each Transparency Report
    - ENTITY_MAP_FKEY                # Identifier for each company
    - AUDITOR_FKEY                   # Unique numeric identifier for each audit firm
    - TRANS_REPORT_AUDITOR_STATE     # ISO code for the country of the auditor
    - AUDITOR_NETWORK                # Name of the auditor network (for grouping and filtration)
    - REPORT_YEAR                    # Fiscal year of the Transparency Report, filtered for 2021
    - NUMBER_OF_DISCLOSED_PIES       # Number of PIEs audited by each firm
    - ENTITY_NAME                    # Name of the audited company for visibility

# Country filters
included_countries:
    - DK  # Denmark
    - CY  # Cyprus
    - FI  # Finland
    - SE  # Sweden
    - LU  # Luxembourg
    - BE  # Belgium
    - EE  # Estonia
    - AT  # Austria
    - NO  # Norway
    - NL  # Netherlands
    - IT  # Italy
    - ES  # Spain
    - IE  # Ireland
    - DE  # Germany
    - MT  # Malta
    - LT  # Lithuania
    - HU  # Hungary
    - LV  # Latvia
    - CZ  # Czech Republic
    - HR  # Croatia
    - SI  # Slovenia
    - SK  # Slovakia
    - FR  # France
    - PL  # Poland
    - PT  # Portugal
    - EL  # Greece
    - RO  # Romania
    - BG  # Bulgaria

# Filter for fiscal year 2021
cs_filter: REPORT_YEAR=2021  # Only include records with REPORT_YEAR equal to 2021

# Output file path for saving the data
output_save_path: 'data/pulled/transparency_report_data_2021.csv'